# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b900f4dbf86ad92cc5b76c92b01423f8a2b54fbb7006d96b71a79d1dd876291721544cde8b4a501d1e89f37b655261e878892601cadf096e1916e2ab4d5e5613

test:
  secret_key_base: 8b9567943005b2a976d52ad1ec2e413644ce6a19a94400beae722bb5804d0800463b153902020c390d0d0199b392b8d768e3421113e6c56bf89093a1bdb8390c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
